api:
  login_url: "http://127.0.0.1:8081/v1/dashboard/auth/login"
  username: "mulyadi@modefashion.id"
  password: "12345!"
  push_url: "http://127.0.0.1:8081/v1/pos/push-transaction"
database:
  host: "127.0.0.1"
  port: 15432
  user: "postgres"
  password: "postgres"
  dbname: "mpos"
  sslmode: "disable"
